### ISSUE TITLE
Failed to configure datasource

### ISSUE THREAD

**Issue by samindaperamuna** [sflpro/notifier#182]
I am working with version 1.7.0 and set up both Postgres and Rabbit as specified on the readme file. I am getting the following error and as no other documentation is available can someone point me in the right direction.

``` Description:
notifier-api_1     | 
notifier-api_1     | Failed to configure a DataSource: no embedded datasource could be configured.
notifier-api_1     | 
notifier-api_1     | Reason: Failed to determine a suitable driver class```

**Comment by dnavre** [comment]
Hi Saminda, sorry for the slow response, it's the holiday season. Can you
please provide your config file's content? I think, there's stuff missing
from it.

**Comment by samindaperamuna** [comment]
```yml
version: '3.5'
services:
  notifier-api:
    image: 'sflpro/notifier-api:1.7.0'
    ports:
      - '9000:9000'
    depends_on:
      - notifier-worker
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgres://localhost:5432/notifier'
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres      
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_RABBITMQ_HOST=localhost
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=password
      - NOTIFIER_QUEUE_ENGINE=rabbit
  notifier-worker:
    image: 'sflpro/notifier-worker:1.7.0'
    restart: on-failure
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgres://localhost:5432/notifier'
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_RABBITMQ_HOST=localhost
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=password
      - NOTIFIER_QUEUE_ENGINE=rabbit
```

This is my compose YML
I connect to other containers for Postgres and RabbitMQ
